name: Lint and Format

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Lint and format frontend
    - name: Lint and format frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run lint
        npm run format:check

    # 4. Format backend
    - name: Format backend
      working-directory: ./backend
      run: |
        npm install
        npm run format:check
